[project]
name = "icpr-contest-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lightning>=2.6.1",
    "prettytable>=3.17.0",
    "torchgeo>=0.9.0",
]
